### ISSUE TITLE
Add support for `revert` commit types

### ISSUE THREAD

**Issue by doomspork** [beam-community/common-config#18]
see: https://github.com/beam-community/common-config/pull/16#pullrequestreview-2137079245

@btkostner @yordis captured this as an issue. I'll circle back to this when I get time.

**Comment by yordis** [comment]
I would remove `chore` moving forward, since that doesn't cause SemVer bump. So only `feat`, `fix`, `refactor`.

For the same reason, I wouldn't include `revert`, since it wouldn't affect SemVer, and in practice, it means that we deprecate a version in Hex that had the code, but that is all.

**Comment by btkostner** [comment]
I'd imagine a revert would cause a new SemVer version to be pushed and a deprecate message on the old Hex version.

If I merge in a `revert` commit, I'd still want to release it with release please which would require it being in the changelog.

**Comment by yordis** [comment]
Actually, you are right! I remember I made a mistake before in Ueberauth that didn't create a new version and the `deprecated` flagging in hex didn't do anything.

I retract my comment.

**Comment by yordis** [comment]
What SemVer version should be changed when reverting, btw?

**Comment by btkostner** [comment]
That's a good question. Off the top of my head, I'd say the patch number which seems to be in line with what [other](https://github.com/semantic-release/commit-analyzer/blob/ebbb68cc1733f7d961a007cb500d07b673212032/lib/default-release-rules.js#L8) [projects](https://github.com/vuejs/core/blob/main/CHANGELOG.md#reverts) [do](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1771-2024-03-28).
